<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8" />
        <title>Ch01-01</title>
    </head>
    <body>
        <img src="https://images.chinatimes.com/newsphoto/2019-11-25/900/20191125001883.jpg">
        <h4>題目：超好吃的食物!</h4>
        <p>
            作者：我(徐崢 10820026)<br>
            監製：我<br>
            找圖：我<br>
            此篇網頁將介紹各種美食佳餚，並搭配圖片和影片加以介紹<br>
            <br>
            <br>
            <br>
            食物，人類所需，沒食物就只能狗帶。但好吃的食物不只是果腹，它代表了情懷。是人類的文化藝術。<br>
            這麼說好了-----<br>
            君子食無求飽，但求一珍，敏於食而慎於味，就有道而正焉，可謂好美食也矣！！！<br>
            <br>
            <br>
            以下為我個人最喜歡的各國美食比較<br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            我最愛的印度美食----印度咖哩角<br>
            <br>
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Samosachutney.jpg/250px-Samosachutney.jpg" /><br>
            <br>
            其餡料可包括用香料調味的馬鈴薯、洋蔥、豌豆和扁豆，還有絞肉（羊肉、牛肉或雞肉），有時亦會添加松子。我最喜歡加辣餡的，蘇胡~😋<br>
            <br>
            <br>
            <a href="http://www.vacationsindia.tw/about-india/cuisine.html">想看更多印度美食介紹點我~</a>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            我最愛的日本美食----日式咖哩飯<br>
            <br>
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/140322_Unzen_Kanko_Hotel_Unzen_Nagasaki_pref_Japan18s.jpg/300px-140322_Unzen_Kanko_Hotel_Unzen_Nagasaki_pref_Japan18s.jpg" /><br>
            <br>
            日式咖哩飯是一種將米飯配上日式咖哩汁一同進食的日本料理。日式咖哩口感香滑濃稠、味道較甜。味道比起印度咖哩其實不怎麼樣，但是，淋巴就喜歡吃甜，所以她就金榜題名喽。🤪<br>
            <br>
            <br>
            <a href="https://allabout-japan.com/zh-tw/article/5446/">想看更多日本美食介紹點我~</a>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            我最愛的美國美食----漢堡<br>
            <br>
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Pork_and_Eggs_with_salad_hamburger.jpg/285px-Pork_and_Eggs_with_salad_hamburger.jpg" /><br>
            <br>
            也被稱作漢堡包，在定義上屬於三明治的一種，現今被普遍視為美式速食的代表。其餡料以漢堡排為主，並附夾上若干配料（以蔬菜和起司為主）和調味料。看過海綿寶寶吧，我會喜歡漢堡是多虧了他們的美味蟹堡，給我漢堡又大又好吃的印象。😂<br>
            <br>
            <br>
            <a href="https://allabout-japan.com/zh-tw/article/5446/">想看更多美國美食介紹點我~</a><br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            以上都是我的主觀介紹<br>
            我也放其他介紹美食的影片給各位<br>
            <br>
            <br>
            <iframe width="1280" height="720" src="https://www.youtube.com/embed/zoXHQh-DPBE" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            <iframe width="1280" height="720" src="https://www.youtube.com/embed/Koa2bretohg" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            <iframe width="1280" height="720" src="https://www.youtube.com/embed/xxuiPlv9akk" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            <br>
            <br>
            雖說沒有介紹的很詳細，但還是應有盡有吧。😂
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            接下來是列出我愛的食物和上面影片所介紹食物的「清單」<br>
            <br>
            <br>
            <ul>
                <li>
                    我愛的食物
                    <ol>
                        <li><b>有甜味的日式咖哩</b></li>
                        <li>香料味珍的印度咖哩角</li>
                        <li>又大又香的美式漢堡</li>
                    </ol><br>

                </li>
                <li>
                    影片裡有介紹到的食物
                    <ol type="I">
                        <li>扁豆燉飯</li>
                        <li>壽司</li>
                        <li>紐約風格披薩</li>
                    </ol>
                </li>
            </ul>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            接下來用「表格」總結我對所有本次所提及食物的評價<br>
            <br>
            <br>
            <table border="1">
                <tr>
                    <td>喜好\美食
                    <td>日式咖哩
                    <td>美式漢堡
                    <td>印度咖哩角
                    <td>扁豆燉飯
                    <td>壽司
                    <td>紐約風格披薩
                <tr>
                    <td>喜歡
                    <td>○
                    <td>○
                    <td>○
                    <td>
                    <td>
                    <td>○
                <tr>
                    <td>普通
                    <td>
                    <td>
                    <td>
                    <td>○
                    <td>
                    <td>
                <tr>
                    <td>不行
                    <td>
                    <td>
                    <td>
                    <td>
                    <td>○
                    <td>
            </table>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <h4>總結：我好像把網頁做得太個人主義啦，沒關係，以後有的是機會😎</h4><br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
        </p>
    </body>    
</html>
